In [1]:
import torch

In [2]:
from classification import LogisticRegression

torch.random.manual_seed(7)
x = torch.rand(100, 20)
w = torch.tensor([[1], [-1]] * 10).float()

y = torch.sigmoid(x @ w).round().int()

model = LogisticRegression(20).fit(x, y, epochs=10000)

In [13]:
from classification import LogisticRegressionRBF

m = LogisticRegressionRBF(x[:100]).fit(x, y, epochs=10000)

In [14]:
from metrics import accuracy

accuracy(y.flatten(), m.predict(x).flatten())

1.0

In [4]:
from classification import SVM

SVM(20).fit(x, y, epochs=10000)

Epoch:     2 | HingeLoss:  1.39612
Epoch:     6 | HingeLoss:  1.37652
Epoch:    12 | HingeLoss:  1.34713
Epoch:    25 | HingeLoss:  1.28344
Epoch:    50 | HingeLoss:  1.16097
Epoch:    99 | HingeLoss:  0.92093
Epoch:   192 | HingeLoss:  0.58328
Epoch:   371 | HingeLoss:  0.56141
Epoch:   718 | HingeLoss:  0.56000
Epoch:  1388 | HingeLoss:  0.56000
Epoch:  2681 | HingeLoss:  0.56000
Epoch:  5178 | HingeLoss:  0.56000
Epoch:  10000 | HingeLoss:  0.56000


SVM(
  (weights): Linear(in_features=20, out_features=1, bias=True)
)

In [5]:
m = SVM(2).fit_by_pegasos(x, y, epochs=1)

In [6]:
m.fit(x, y, epochs=1)

Epoch:     1 | HingeLoss:  0.56000


SVM(
  (weights): Linear(in_features=2, out_features=1, bias=True)
)

In [7]:
from sklearn.datasets import make_blobs

x, y = make_blobs(100, centers=2)
x, y = torch.tensor(x), torch.tensor(y)

In [8]:
torch.random.manual_seed(7)
x, y = make_blobs(100, centers=2)
x, y = torch.tensor(x), torch.tensor(y)
m = SVM(2).fit(x, y, epochs=1000)
print(m.predict(x))
from metrics import accuracy
print(accuracy(y, m.predict(x)))

Epoch:     1 | HingeLoss:  1.54503
Epoch:     3 | HingeLoss:  1.53481
Epoch:     6 | HingeLoss:  1.51947
Epoch:    10 | HingeLoss:  1.49903
Epoch:    18 | HingeLoss:  1.45814
Epoch:    30 | HingeLoss:  1.39680
Epoch:    50 | HingeLoss:  1.29457
Epoch:    83 | HingeLoss:  1.12590
Epoch:   138 | HingeLoss:  0.84477
Epoch:   226 | HingeLoss:  0.53472
Epoch:   372 | HingeLoss:  0.50404
Epoch:   610 | HingeLoss:  0.50000
Epoch:  1000 | HingeLoss:  0.50000
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
0.5


In [9]:
m(x)

tensor([[2.0023],
        [2.0784],
        [1.4227],
        [1.9286],
        [2.0567],
        [2.1495],
        [1.8379],
        [2.0944],
        [1.6704],
        [1.3474],
        [1.7572],
        [1.8779],
        [2.2381],
        [1.5927],
        [1.5126],
        [1.9969],
        [1.6448],
        [2.4637],
        [1.5459],
        [1.5134],
        [1.4913],
        [1.5335],
        [2.1321],
        [1.3230],
        [1.7837],
        [2.0808],
        [2.2218],
        [1.8099],
        [1.9306],
        [2.0251],
        [2.3380],
        [1.0153],
        [2.0470],
        [1.9923],
        [1.5465],
        [2.2202],
        [2.2597],
        [1.9341],
        [1.5863],
        [2.1705],
        [1.5071],
        [1.2209],
        [1.3813],
        [1.8552],
        [1.9671],
        [1.6614],
        [1.0808],
        [2.1191],
        [1.6468],
        [1.6151],
        [1.9682],
        [1.6674],
        [1.3048],
        [1.6769],
        [2.3668],
        [1

In [10]:
from sklearn.svm import SVC

In [11]:
model = SVC()

In [12]:
model.fit(x, y)

SVC()

In [13]:
model.predict(x)

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1])

In [16]:
print(accuracy(y, torch.tensor(model.predict(x))))

1.0


In [9]:
m = SVM(2).fit(x, y, epochs=1000)

Epoch:     1 | HingeLoss:  0.50000
Epoch:     3 | HingeLoss:  0.50000
Epoch:     6 | HingeLoss:  0.50000
Epoch:    10 | HingeLoss:  0.50000
Epoch:    18 | HingeLoss:  0.50000
Epoch:    30 | HingeLoss:  0.50000
Epoch:    50 | HingeLoss:  0.50000
Epoch:    83 | HingeLoss:  0.50000
Epoch:   138 | HingeLoss:  0.50000
Epoch:   226 | HingeLoss:  0.50000
Epoch:   372 | HingeLoss:  0.50000
Epoch:   610 | HingeLoss:  0.50000
Epoch:  1000 | HingeLoss:  0.50000


In [10]:
m.predict(x)

/Users/victorbarbarich/PycharmProjects/mathml/src/nueramic_mathml/ml/classification.py:294: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  return (self.weights(x).sign().int().flatten() + 1) // 2


tensor([0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
        1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
        1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
        0, 0, 1, 0], dtype=torch.int32)